// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh_STy2EdCDTaCQwDOEN3qHSlm0cZ_y4E',
    appId: '1:526870881726:web:de4ea55404a906583cc5ef',
    messagingSenderId: '526870881726',
    projectId: 'devsociety-411801',
    authDomain: 'devsociety-411801.firebaseapp.com',
    storageBucket: 'devsociety-411801.appspot.com',
    measurementId: 'G-DPYH0S2LL3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0aXpn6Aki3ZpOCjLR522J9Y90wqAu7JI',
    appId: '1:526870881726:android:805cd527b9811e683cc5ef',
    messagingSenderId: '526870881726',
    projectId: 'devsociety-411801',
    storageBucket: 'devsociety-411801.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw5PGw6SZge1E2Wnbpgwq-83hhyL6qj50',
    appId: '1:526870881726:ios:3df159e4fe80ec2b3cc5ef',
    messagingSenderId: '526870881726',
    projectId: 'devsociety-411801',
    storageBucket: 'devsociety-411801.appspot.com',
    iosClientId: '526870881726-rln8sunptbqqiahivhk0ti4sefduc7nu.apps.googleusercontent.com',
    iosBundleId: 'com.thanksnhang.devsociety',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw5PGw6SZge1E2Wnbpgwq-83hhyL6qj50',
    appId: '1:526870881726:ios:c589a4cac5c218803cc5ef',
    messagingSenderId: '526870881726',
    projectId: 'devsociety-411801',
    storageBucket: 'devsociety-411801.appspot.com',
    iosClientId: '526870881726-0846dg962bsja1qfni5thr5deaa3080k.apps.googleusercontent.com',
    iosBundleId: 'com.thanksnhang.devsociety.RunnerTests',
  );
}
